import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F9FAFB',
  },
  content: {
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 24,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 18,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  schoolBadge: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 4,
  },
  schoolBadgeImage: {
    width: 28,
    height: 28,
  },
  schoolName: {
    fontSize: 16,
    fontWeight: '700',
    color: '#111827',
  },
  headerIconButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 20,
    shadowColor: '#111827',
    shadowOpacity: 0.06,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
    marginBottom: 10,
  },
  stripeLogo: {
    fontSize: 28,
    fontWeight: '700',
    color: '#635BFF',
    textAlign: 'center',
  },
  stripeTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#111827',
    textAlign: 'center',
    marginTop: 10,
  },
  stripeDescription: {
    fontSize: 13,
    color: '#6B7280',
    textAlign: 'center',
    marginTop: 8,
    lineHeight: 18,
  },
  stripeButton: {
    marginTop: 16,
    height: 44,
    width: 180,
    borderRadius: 15,
    backgroundColor: '#EC4899',
    alignSelf: 'center',
  },
  stripeButtonText: {
    color: '#FFFFFF',
    fontWeight: '600',
  },
  // Connected State Styles
  connectedCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 20,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  schoolInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 24,
    borderBottomColor: '#E5E7EB',
    borderBottomWidth: 1,
    paddingBottom: 20,
  },
  schoolIconContainer: {
    width: 40,
    height: 40,
    marginRight: 12,
  },
  schoolIcon: {
    width: '100%',
    height: '100%',
    borderRadius: 8,
    marginTop: 2,
  },
  schoolInfoText: {
    flex: 1,
  },
  connectedSchoolName: {
    fontSize: 14,
    fontWeight: '700',
    color: '#111827',
  },
  accountId: {
    fontSize: 12,
    color: '#9CA3AF',
    marginTop: 2,
  },
  balanceContainer: {
    marginBottom: 24,
  },
  balanceLabel: {
    fontSize: 14,
    color: '#6B7280',
    marginBottom: 4,
  },
  balanceAmount: {
    fontSize: 40,
    fontWeight: '700',
    color: '#000000',
    letterSpacing: -1,
  },
  currencyLabel: {
    fontSize: 14,
    color: '#111827',
    marginTop: 4,
  },
  collectButton: {
    backgroundColor: '#EC4899',
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    width: '100%',
  },
  collectButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  manageItemsText: {
    color: '#EC4899',
    fontSize: 13,
    fontWeight: '500',
    marginTop: 4,
  },
  // Transactions
  transactionsSection: {
    marginTop: 8,
    flex: 1,
  },
  emptyStateContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 40,
  },
  emptyStateIcon: {
    width: 64,
    height: 64,
    marginBottom: 16,
    opacity: 0.5,
  },
  emptyStateTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#111827',
    marginBottom: 8,
  },
  emptyStateSubtitle: {
    fontSize: 14,
    color: '#6B7280',
    textAlign: 'center',
  },
  transactionsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  transactionsTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#111827',
  },
  seeAllText: {
    fontSize: 14,
    color: '#EC4899',
    fontWeight: '500',
  },
  transactionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  transactionIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FCE7F3',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  transactionInfo: {
    flex: 1,
  },
  transactionName: {
    fontSize: 14,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 2,
  },
  transactionDate: {
    fontSize: 14,
    color: '#6B7280',
  },
  transactionAmountColumn: {
    alignItems: 'flex-end',
  },
  transactionAmount: {
    fontSize: 14,
    fontWeight: '600',
    color: '#111827',
    marginBottom: 2,
  },
  transactionItems: {
    fontSize: 12,
    color: '#6B7280',
  },
  dateRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  dateText: {
    fontSize: 16,
    color: '#111827',
    fontWeight: '500',
  },
  totalAmountText: {
    fontSize: 14,
    color: '#6B7280',
  },
  transactionIconBlue: {
    backgroundColor: '#E0E7FF',
  },
  rowCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  rowLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  rowIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  rowIconImage: {
    width: 44,
    height: 40,
  },
  rowTextWrap: {
    flex: 1,
  },
  rowTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#111827',
  },
  rowSubtitle: {
    fontSize: 13,
    color: '#EC4899',
    marginTop: 2,
    fontWeight: '600',
  },
  rowSecondaryTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#111827',
  },
  rowSecondarySubtitle: {
    fontSize: 13,
    color: '#EC4899',
    marginTop: 2,
    fontWeight: '600',
  },
  closeButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
});
