import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 20,
  },
  // Segmented Progress Bars Container
  progressBarsContainer: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 20,
    marginTop: 10,
  },
  progressBarSegment: {
    flex: 1,
    height: 3,
    backgroundColor: '#E0E0E0',
    borderRadius: 2,
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: '#E91E63',
    borderRadius: 2,
  },
  logoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  logo: {
    width: 24,
    height: 24,
    borderRadius: 6,
    marginRight: 6,
    marginTop: 2,
    resizeMode: 'contain',
  },
  logoText: {
    fontSize: 16,
    fontWeight: '500',
    color: '#333',
  },
  slide: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  iconContainer: {
    height: height * 0.35,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  onboardingImage: {
    width: width * 0.8,
    height: height * 0.35,
    resizeMode: 'contain',
  },
  // Phone with Card Icon Styles
  phoneIcon: {
    width: 160,
    height: 200,
    backgroundColor: '#2C2C2E',
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 20 },
    shadowOpacity: 0.3,
    shadowRadius: 30,
    elevation: 15,
    transform: [{ rotateY: '-15deg' }, { rotateX: '5deg' }],
  },
  cardIcon: {
    width: 100,
    height: 70,
    backgroundColor: '#E91E63',
    borderRadius: 12,
    shadowColor: '#E91E63',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.4,
    shadowRadius: 15,
    elevation: 10,
  },
  // User Icon Styles
  userIconContainer: {
    width: 180,
    height: 180,
    backgroundColor: '#2C2C2E',
    borderRadius: 90,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 20 },
    shadowOpacity: 0.3,
    shadowRadius: 30,
    elevation: 15,
  },
  userIconTop: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#E91E63',
    marginBottom: 10,
    shadowColor: '#E91E63',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 8,
  },
  userIconBottom: {
    width: 70,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#F48FB1',
    shadowColor: '#E91E63',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 8,
  },
  // Chart Icon Styles
  chartIconContainer: {
    width: 180,
    height: 180,
    backgroundColor: '#2C2C2E',
    borderRadius: 90,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 20 },
    shadowOpacity: 0.3,
    shadowRadius: 30,
    elevation: 15,
  },
  chartPiece1: {
    position: 'absolute',
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#757575',
    top: 50,
    left: 30,
  },
  chartPiece2: {
    position: 'absolute',
    width: 70,
    height: 70,
    backgroundColor: '#9E9E9E',
    top: 40,
    right: 35,
    transform: [{ rotate: '45deg' }],
    borderTopLeftRadius: 35,
    borderTopRightRadius: 35,
  },
  chartCircle: {
    position: 'absolute',
    width: 90,
    height: 90,
    borderRadius: 45,
    borderWidth: 15,
    borderColor: '#E91E63',
    borderTopColor: 'transparent',
    borderLeftColor: 'transparent',
    transform: [{ rotate: '-45deg' }],
    top: 45,
    left: 45,
  },
  contentContainer: {
    alignItems: 'center',
    paddingHorizontal: 4,
  },
  title: {
    fontSize: 26,
    fontWeight: '700',
    color: '#000',
    textAlign: 'center',
    marginBottom: 16,
    lineHeight: 32,
  },
  description: {
    fontSize: 16,
    color: '#000',
    textAlign: 'center',
    lineHeight: 24,
    paddingHorizontal: 4,
  },
  footer: {
    paddingHorizontal: 30,
    paddingBottom: 20,
  },
  nextButton: {
    backgroundColor: '#E91E63',
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
    shadowColor: '#E91E63',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  nextButtonText: {
    color: '#FFF',
    fontSize: 17,
    fontWeight: '600',
  },
  loginContainer: {
    marginTop: 10,
    alignItems: 'center',
  },
  loginText: {
    fontSize: 15,
    color: '#000',
    fontWeight: '500',
  },
  loginLink: {
    color: '#E91E63',
    fontWeight: '600',
  },
});

export default styles;
